name: People Are My Business
favicon: null
layout_spectrum: 0.20930130453780293
typography_spectrum: 0.397862856509164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11149542639032006
  lightness: 0.1979990324471146
  saturation: 0.049398627365008
  rhythmicContrast: 0.6080228493083268
purpose: []
