analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#033977'
    - '#d21825'
    - '#536aa0'
    - '#ce7378'
  brandStrength: 0.3125
  lightness: 0.1979990324471146
  rhythmicContrast: 0.6080228493083268
  saturation: 0.125
cta: {}
layout_spectrum: 0.209301
name: People Are My Business
opengraph: {}
purpose: []
typography_spectrum: 0.49
